add support for SetupHelper v4

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -47,6 +47,7 @@ source "/data/SetupHelper/CommonResources"
 
 #### end of lines to include SetupHelper
 
+####### this is duplicate to code in CommonResources -- keep in case SetupHelepr has not been updated
 # prevent installing if not a Raspberry Pi
 if [ -f /etc/venus/machine ]; then
     machine=$(cat /etc/venus/machine)
@@ -57,7 +58,7 @@ if [ -z $machine ]; then
         scriptAction='UNINSTALL'
     else
         logMessage "can't determine Venus device type - exiting"
-        exit
+        exit $EXIT_INCOMPATIBLE_PLATFOM
     fi
 elif [ $machine != "raspberrypi2" ] && [ $machine != "raspberrypi4" ]; then
     if [ -f "$installedFlag" ]; then
@@ -65,7 +66,7 @@ elif [ $machine != "raspberrypi2" ] && [ $machine != "raspberrypi4" ]; then
         scriptAction='UNINSTALL'
     else
         logMessage "$packageName not compatible with $machine - exiting"
-        exit
+        exit $EXIT_INCOMPATIBLE_PLATFOM
     fi
 fi
 
@@ -87,7 +88,7 @@ if [ $scriptAction == 'NONE' ] ; then
     if [ $scriptAction == 'NONE' ] || [ $scriptAction == 'PROMPT' ]; then
         echo
         echo "This script supports the following displays:"
-        echo "    (R) Raspberry PI touchscreen"
+        echo "    (R) Raspberry PI touchscreen (DSI)"
         echo "    (0) HDMI display connected to port 0 (closest to power connector)"
         echo "    (1) HDMI display connected to port 1"
         echo
@@ -115,21 +116,49 @@ fi
 
 #### installing
 if [ $scriptAction == 'INSTALL' ] ; then
-    # set defaults if options have not been set before
-    # RPI display
-    if [ ! -f "$setupOptionsDir/optionsSet" ]; then
-        logMessage "install selected but no options have been set - using defaults"
-        echo "RPI" > "$setupOptionsDir/displayToControl"
-        touch "$setupOptionsDir/optionsSet"
+
+	# the overlay is needed to automatically discover display type
+	if [ ! -f "$overlayFile" ]; then
+		logMessage "installing RPI Display Backlight overlay"
+		cp "$scriptDir/rpi-backlight-overlay.dtb" "$overlayFile"
+		rebootNeeded=true
+		waitForOverlay=true
+	else
+		waitForOverlay=false
+	fi
+
+	# get selected display from NV storage
+	if [ -f $setupOptionsDir/displayToControl ]; then
+		displayToControl=$(cat $setupOptionsDir/displayToControl)
+	# options not yet set - use auto-discovery
+	else
+		if $waitForOverlay ; then
+			logMessage "install options have not been set - installng overlay and rebooting for auto discovery"
+			runAgain=true
+			# stop setup now and come back later to finish
+			endScript
+		# with overlay in place auto-discover display type		
+		else
+			if [ -e /sys/class/backlight/rpi_backlight ]; then
+				logMessage "auto-discover display type RPI"
+				displayToControl='RPI'
+			else
+				logMessage "auto-discover display type HDMI 0"
+				displayToControl="HDMI 0"
+			fi
+			echo $displayToControl > "$setupOptionsDir/displayToControl"
+		fi
     fi
 
-    if [ -f $setupOptionsDir/displayToControl ]; then
-        displayToControl=$(cat $setupOptionsDir/displayToControl)
-    else
-        logMessage "++ ERROR: no display specified - can't continue - install again"
-        exit
-    fi
-    logMessage "++ Installing RPI display enhancements for display: $displayToControl"
+echo "#### displayToControl $displayToControl"
+
+	if [ -z "$displayToControl" ]; then
+		logMessage "++ ERROR: no display specified - can't continue - install again"
+		exit $EXIT_ERROR
+	fi
+
+
+    logMessage "++ Installing display enhancements for display: $displayToControl"
     # modify config.txt
     #   make sure hdmi_blanking is enabled
     #   ditto for disable_overscan
@@ -166,18 +195,12 @@ if [ $scriptAction == 'INSTALL' ] ; then
         rm $configFile.tmp
     fi
 
-    # install backlight overlay before doing any other installs
     case $displayToControl in
         RPI)
             installDimming=true
             logMessage "disabling AutoBrightness"
             dbus -y com.victronenergy.settings /Settings/Gui/AutoBrightness SetValue 0 > /dev/null
             blankDevice="/sys/class/backlight/rpi_backlight/bl_power"
-            if [ ! -f "$overlayFile" ]; then
-                logMessage "installing RPI Display Backlight overlay"
-                cp "$scriptDir/rpi-backlight-overlay.dtb" "$overlayFile"
-                rebootNeeded=true
-            fi
             ;;
         "HDMI 0")
             installDimming=false
@@ -238,6 +261,13 @@ if [ $scriptAction == 'UNINSTALL' ] ; then
         rm -f $dimDeviceFile
         restartGui=true
     fi
+	# normally, we'd reboot after removing the overlay file
+	#	but the overlay shouldn't have any affect on system behavior
+	#	so waiting until the next reboot cycle should be fine
+    if [ -f "$overlayFile" ]; then
+		logMessage "removing $overlayFile"
+		rm -f "$overlayFile"
+	fi
 fi
 
 #thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
